### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-compute#2]
Thanks for this! I tried it out with a simple R script called `test.R` that just contains `2 + 2`.

`civis-compute submit test.R`
`civis-compute status 8050758`

The log is:

```
log file:
  [2017-11-10T19:33:41.000Z] Queued
  [2017-11-10T19:33:42.000Z] Running
  [2017-11-10T19:33:43.000Z] Dedicating resources
  [2017-11-10T19:33:45.000Z] Downloading code and container
  [2017-11-10T19:33:46.000Z] Executing script
  [2017-11-10T19:33:46.000Z] Traceback (most recent call last):
  [2017-11-10T19:33:46.000Z]   File "/usr/local/bin/civis", line 11, in <module>
  [2017-11-10T19:33:46.000Z]     sys.exit(main())
  [2017-11-10T19:33:46.000Z]   File "/usr/local/lib/python2.7/dist-packages/civis/cli/__main__.py", line 334, in main
  [2017-11-10T19:33:46.000Z]     cli = generate_cli()
  [2017-11-10T19:33:46.000Z]   File "/usr/local/lib/python2.7/dist-packages/civis/cli/__main__.py", line 229, in generate_cli
  [2017-11-10T19:33:46.000Z]     spec = retrieve_spec_dict()
  [2017-11-10T19:33:46.000Z]   File "/usr/local/lib/python2.7/dist-packages/civis/cli/__main__.py", line 201, in retrieve_spec_dict
  [2017-11-10T19:33:46.000Z]     modified_time = os.path.getmtime(_CACHED_SPEC_PATH)
  [2017-11-10T19:33:46.000Z]   File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
  [2017-11-10T19:33:46.000Z]     return os.stat(filename).st_mtime
  [2017-11-10T19:33:46.000Z] OSError: [Errno 2] No such file or directory: '/root/.civis_api_spec.json'
  [2017-11-10T19:33:47.000Z] Memory statistics are unavailable
  [2017-11-10T19:33:47.000Z] Error on job: Process ended with an error, exiting: 1.
  [2017-11-10T19:33:47.000Z] Failed
```

**Comment by beckermr** [comment]
This is not an R error. It appears the python client trying to pull a cached spec when none exists. This ticket should be filed on the python client board.

**Comment by beckermr** [comment]
See this issue: https://github.com/civisanalytics/civis-python/issues/179.

Once the above issue is addressed, a new client version is pushed, and the datascience-r container works, we can close this issue.

**Comment by beckermr** [comment]
Looks like a new client version will be released later this week which will address this issue.

**Comment by patr1ckm** [comment]
I can PR to datascience-r when the new python client releases.

**Comment by beckermr** [comment]
Cool. Leaving this open as a reminder.

**Comment by beckermr** [comment]
Closing this since datascience-r has now been updated.
